### ISSUE TITLE
the bug in workout 

### ISSUE THREAD

**Issue by Lucylea** [kinetic-fit/fit-android-issues#21] opened 2020-03-27 15:22 UTC
**Describe the bug**
I did the High Cadence Tempo 6*10 workout, in the last 10 minutes training, It should be lower intensity, but the power target and cadence target is showing higher data. the code of this workout need to be revised. 

**To Reproduce**
1. doing the workout "High Cadence Tempo 6*10"
2. the last 10 minutes should be lower power and cadence target, but the target repeat showing at high power and cadence. 

**Expected behavior**
in the last 10 minutes, the power and cadence target should be corrected

**Screenshots**
not available

**Smartphone (please complete the following information):**
 - Device: Oneplus 8
 - Oxygen OS 10.3.1
 - Kinetic Fit Version 2.4.1

**Trainer (please complete the following information):**
- Road machine smart 2
- Sensor black

**Additional context**
no

**Comment by Lucylea** [comment] 2020-03-29 06:34
Expected behavior
in the last 10 minutes of this training, it begins with lower power and cadence target, but after 2 minitues, the target of power and cadence is increased to the same as 6 interval target. 
Do I make things clear?

**Comment by Lucylea** [comment] 2020-03-30 12:47
Today I select other workout, (sub Threshold 5*10) and met the same problem. in the last period, it should be the cooling down phase (you can see in the screenshot). but after 3 minutes, the target power is raising from 65w to 124w, which is the sub-Threshold power. 

Screenshot
![image](https://user-images.githubusercontent.com/45616004/77913543-04a1ea80-72c7-11ea-97b9-caed7c088f73.png)

**Comment by lexicalninja** [comment] 2020-03-30 14:26
OK. this is a duplicate of #16. I will be closing this and any work done will be indicated in that thread. Thank you for the reports and trying with different workouts

**Closed as completed by lexicalninja** 2020-03-30 14:26 UTC
Labels: duplicate
