### ISSUE TITLE
Workout sequence not correct and timing wrong on logged data

### ISSUE THREAD

**Issue by RoyalPeddler** [kinetic-fit/fit-android-issues#16] opened 2020-02-25 08:24 UTC
**Describe the bug**
I noticed while using one of the inbuilt workouts (On the Rivet) that the target power level / recovery sequencing was incorrect towards the end of the workout. When the main workout finished and moves to the 10 x minute cooldown period at the end, the intervals and power targets continued to alternate at 60 second intervals, instead of a  single10 min cooldown interval /power target. 

Also when I exported the data to CSV I could see that it registered the 10 minute warmup prior to the main workout at 1200sec instead of 600sec. 

Not a big issue but these did not happen when using the main android app. 

**To Reproduce**
1.Carry out 'On the Rivet' in built workout.
2. Export the workout to csv at the end.

**Expected behavior**
Warm down period to be 1 x single 10 minute interval, instead of 10 x 1 minute intervals

**Screenshots**
Not applicable

**Smartphone (please complete the following information):**
 - Device: [Sony Xperia XZ)
 - OS: [Android 8.0.0]
 - Kinetic Fit Version [Beta 2.3.3 (227)]

**Trainer (please complete the following information):**
- Trainer: [Smart Trainer]
- Firmware Version [e.g. v2.1]

**Comment by lexicalninja** [comment] 2020-02-25 17:17
Thanks for the report. 

I will look into the warmup time issue. 

I will need to look at the interval problem and see what it is coded at in the database. It may have been a migration issue. I will get back to you once I have a chance to try and reproduce the issue

**Comment by lexicalninja** [comment] 2020-02-28 16:20
I believe 229 may have fixed the issue. I am working on 230 build this morning and it is definitely fixed in this build. I am running the On the Rivet workout right now to try and figure out what is happening with the intervals there and will hopefully have a fix soon. 

Please let me know if the CSV issue is fixed over the weekend

**Comment by RoyalPeddler** [comment] 2020-02-28 16:28
OK thanks for the update. I'll see I can try it out over the weekend.

Best regards

Ian

**Comment by RoyalPeddler** [comment] 2020-03-02 10:22
Hi I did a session last night and can confirm that the warmup duration was
recorded correctly at 600sec when exported to CSV.

Thanks

Ian

**Comment by lexicalninja** [comment] 2020-03-02 17:39
thanks. I will mark this as a bug and try and figure out the last intervals issue.

**Comment by jacco411** [comment] 2020-03-27 14:42
I'm on 2.4.1 (230). I am also having similar issues with not getting into the cool down part of a workout. I did one on Wednesday - Criss Cross Super threshold 2x10. It skipped the "rest" interval between the 10 minute Threshold work and also never went into the cool down. I've been having this problem for several weeks now.

**Comment by Lucylea** [comment] 2020-04-02 15:22
I have tried Kinetic Fitness test 4*2, and Criss cross threshold 1*12 workout tonight, which turns out that the planned power graph at the bottom GUI doesn't match the target power and cadence in the cool down process. 
for example. in the Kinetic Fitness test 4*2 workout, in the last 10 minutes, the power graph is a smooth cooling down process, whereas in the target value, there are 4 minutes cooling down + 2 minutes intervals + 4 minutes cooling down. 
And in Criss cross threshold 1*12 workout, it is complicated to describe the last 10 minutes of actual value of taget power and cadence.

**Comment by lexicalninja** [comment] 2020-04-02 15:35
@Lucylea thank you for trying all those. I am working on figuring this issue out right now and this is extremely helpful. I will be working on this today to try and get it fixed. It seems that the interval data is correct, but the calculations that set the target power are not using the correct interval as the graph. I will let you know how things go later today.

Thanks again.

**Comment by lexicalninja** [comment] 2020-04-02 18:13
@RoyalPeddler @jacco411 @Lucylea 
I have worked on this issue today and believe it to be solved. Please download version 2.5.4 (235) when it becomes available and let me know. It should also fix the dat displayed in the popups before an interval starts to give you the correct power values.

Please let me know if you are still experiencing this and what workout you are running. Thanks

**Comment by Lucylea** [comment] 2020-04-03 15:20
Thank you, I updated the app, but kinetic fit 2.5.4 is not available in the play store, so I updated the app to 2.5.3 version.
I tried Criss cross threshold 2 plus 10 workout, the sequence and timing work well until the first cooling down come, that is at 12 minutes. it should be cooling phase, but the power target repeat the previous 4 minutes power (85% FTP and 100% FTP) twice (8 mintues). but the cooling phase time < 8 mintues, so it affects the following workout. so the sequence and timing does not match the the power graph at the bottom of GUI.

**Comment by lexicalninja** [comment] 2020-04-03 15:31
It was not changed until version 2.5.4, so you will need to check for that version to make it to the store for you. It was basically grabbing the intervals for the first two hills and valleys and using those instead of the cool down, so that is what you see in the all of the interval workouts.

Once 2.5.4 gets to you and you do your regular workout, it should be fixed for you. It may take a little more time than usual right now. Thanks

**Comment by Lucylea** [comment] 2020-04-04 14:11
Yes, I tried the previous bug workouts, it turns out this bug has been fixed. Thank you for doing this.&nbsp;


 
---Original---

**Comment by lexicalninja** [comment] 2020-04-04 16:01
Excellent. Thank you for your help in fixing this.

**Closed as completed by lexicalninja** 2020-04-04 16:01 UTC
Labels: bug

**Comment by RoyalPeddler** [comment] 2020-04-23 13:04
Hi

I'm not sure if this is a separate issue but I've noticed that teh workouts
showing up on my app are not ones I have ridden, there are multiple ones
for each day making me thing that maybe all Beta users workouts are being
uploaded to my account somehow?

Thanks

Ian

**Comment by lexicalninja** [comment] 2020-04-23 14:13
This is a separate issue that came up in #32. the new version should force a log out/ log in if it sees this, but logging out will fix this. Details are in the closed issue linked. 

Please be sure to make each bug you find a separate issue and do a quick search on the issues page to see if it is already opened. That way we can have a single thread for each bug to make sure we don't talk at cross purposes.

Thanks for reporting your issues, it helps make Fit better for everyone. I greatly appreciate it

**Comment by RoyalPeddler** [comment] 2020-04-23 14:26
Ok thanks for getting back to me. Sorry I should have checked out the issue
page first, ill do that next time.

Thanks

**Comment by lexicalninja** [comment] 2020-04-23 14:27
No worries. We are all working together and learning here 😄
