### ISSUE TITLE
Can't Log On When Using Cellular Data

### ISSUE THREAD

**Issue by SalomonSuspect** [kinetic-fit/fit-android-issues#8] opened 2019-12-17 23:31 UTC
**Describe the bug**
The App will not let me log in and continues to return me to the log on page when trying to log on when on cellular data. 

**To Reproduce**
1. Open app
2. Enter User Name and Password
3. Select "Log On"
4. App goes to loading screen and then returns to the Log On Screen after a few seconds

**Expected behavior**
The app should log me in

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Galaxy S8
 - OS: Android 9
 - Version 9

**Trainer (please complete the following information):**
- Trainer: Road Machine Control

**Comment by lexicalninja** [comment] 2019-12-18 15:26
Duplicate of #7 
Closing this here and explaining on first issue. Thanks for the report

**Closed as completed by lexicalninja** 2019-12-18 15:26 UTC
